In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
import pandas as pd
df=pd.read_csv('/content/Product_purchase (3).csv')
df

,User ID,Gender,Age,EstimatedSalary,Purchased
0,15624510,Male,19,19000,0
1,15810944,Male,35,20000,0
2,15668575,Female,26,43000,0
3,15603246,Female,27,57000,0
4,15804002,Male,19,76000,0
...,...,...,...,...,...
395,15691863,Female,46,41000,1
396,15706071,Male,51,23000,1
397,15654296,Female,50,20000,1
398,15755018,Male,36,33000,0


In [ ]:
df=pd.read_csv('/content/Product_purchase (3).csv')
x=df.iloc[:,[2,3]].values
y=df.iloc[:,4].values

In [ ]:
print(df.columns[[2,3]])
print(df.columns[4])

Index(['Age', 'EstimatedSalary'], dtype='object')
Purchased


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
print(x_train)
print(x_test)

[[ 0.58164944 -0.88670699]
 [-0.60673761  1.46173768]
 [-0.01254409 -0.5677824 ]
 [-0.60673761  1.89663484]
 [ 1.37390747 -1.40858358]
 [ 1.47293972  0.99784738]
 [ 0.08648817 -0.79972756]
 [-0.01254409 -0.24885782]
 [-0.21060859 -0.5677824 ]
 [-0.21060859 -0.19087153]
 [-0.30964085 -1.29261101]
 [-0.30964085 -0.5677824 ]
 [ 0.38358493  0.09905991]
 [ 0.8787462  -0.59677555]
 [ 2.06713324 -1.17663843]
 [ 1.07681071 -0.13288524]
 [ 0.68068169  1.78066227]
 [-0.70576986  0.56295021]
 [ 0.77971394  0.35999821]
 [ 0.8787462  -0.53878926]
 [-1.20093113 -1.58254245]
 [ 2.1661655   0.93986109]
 [-0.01254409  1.22979253]
 [ 0.18552042  1.08482681]
 [ 0.38358493 -0.48080297]
 [-0.30964085 -0.30684411]
 [ 0.97777845 -0.8287207 ]
 [ 0.97777845  1.8676417 ]
 [-0.01254409  1.25878567]
 [-0.90383437  2.27354572]
 [-1.20093113 -1.58254245]
 [ 2.1661655  -0.79972756]
 [-1.39899564 -1.46656987]
 [ 0.38358493  2.30253886]
 [ 0.77971394  0.76590222]
 [-1.00286662 -0.30684411]
 [ 0.08648817  0.76590222]
 

In [ ]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier(criterion='entropy',max_depth=None,min_samples_split=5,min_samples_leaf=2)
model.fit(x_train,y_train)
print(model)
y_pred_dec=model.predict(x_test)
y_pred_dec
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_dec)
print(cm)
from sklearn.metrics import accuracy_score
print("decision tree",accuracy_score(y_test,y_pred_dec))


DecisionTreeClassifier(criterion='entropy', min_samples_leaf=2,
                       min_samples_split=5)
[[66  2]
 [ 6 26]]
decision tree 0.92


In [ ]:
from sklearn.linear_model import LogisticRegression
modellr=LogisticRegression(random_state=0)
model.fit(x_train,y_train)
print(modellr)
y_pred_lr=model.predict(x_test)
y_pred_lr
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred_lr)
print(cm)
from sklearn.metrics import accuracy_score
print("Logistic Regression",accuracy_score(y_test,y_pred_lr))


LogisticRegression(random_state=0)
[[64  4]
 [ 6 26]]
Logistic Regression 0.9


In [ ]:
from sklearn.ensemble import RandomForestClassifier
RFmodel=RandomForestClassifier(n_estimators=200,criterion="entropy",random_state=0)
RFmodel.fit(x_train,y_train)
y_pred_rf=RFmodel.predict(x_test)
y_pred_rf
from sklearn.metrics import confusion_matrix
cmrf=confusion_matrix(y_test,y_pred_rf)
print(cmrf)
from sklearn.metrics import accuracy_score
print("Random Forest",accuracy_score(y_test,y_pred_rf))


[[64  4]
 [ 4 28]]
Random Forest 0.92


In [10]:
from sklearn.svm import SVC
#Create svm classifier object
#model=svc(kernel="rbf",c=1.0,gamma="scale",random_state=0)
#model=svc(kernel="linear") #hyperparameter tuning
model=SVC(kernel="poly",degree=3)
#model=SVC(kernel="rbf")
#training the model
#model=SVC(kernel="rbf")
model.fit(x_train,y_train)
print(model)

SVC(kernel='poly')


In [12]:
model=SVC(kernel="rbf")
model.fit(x_train,y_train)
print(model)



SVC()


In [14]:
model=SVC(kernel="linear")
model.fit(x_train,y_train)
print(model)

SVC(kernel='linear')


In [ ]:
y_pred_svm=model.predict(x_test)
print(y_pred_svm)
from sklearn.metrics import confusion_matrix
cm_sv=confusion_matrix(y_test,y_pred_rf)
print(cm_sv)